name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11  # Change this to your desired Java version

    - name: Compile and run tests
      run: |
        ls -a
        cd ./Algorithms

        # Compile your Java classes
        javac -cp .:junit.jar.java  ./src/tests/Sample.java 

        # Run JUnit tests
        java -cp .:junit.jar:hamcrest.jar org.junit.runner.JUnitCore ./src/tests/Sample

