name: first
on: push

jobs:
  job1:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: set up checkout
        uses: actions/checkout@v2
      - name: DesigniteJava
        # You may pin to the exact commit or the version.
        # uses: DesigniteTools/DJAction@5de0ca090d14125c6057ba4ec74563c1020ca372
        uses: DesigniteTools/DJAction@v1.0.1
    
                
