name: Format Java Code

on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup google-java-format
        id: setup-google-java-format
        uses: thecanadianroot/action-setup-google-java-format@v1
        with:
          token: ${{ github.token }} # optional
          install-path: ${{ github.workspace }} # optional
          version: latest # optional
          ignore-cached-install: false # optional
