name: Format

on: [push]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  testing:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
      - run: |
          cd ./Algorithms
          ls -a
