name: Format Java Code

on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Prettier Java Format
      uses: tsar-boomba/prettier-java-action@v1.1.0
