name: Format Java Code

on:
  push:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup google-java-format
        id: setup-google-java-format
        uses: thecanadianroot/action-setup-google-java-format@v1
        with:
          token: ${{ github.token }} # optional
          install-path: ${{ github.workspace }} # optional
          version: latest # optional
          ignore-cached-install: false # optional
      - name: Checkstyle for Java
        # You may pin to the exact commit or the version.
        # uses: dbelyaev/action-checkstyle@6765c03db05d6a4efa631bc05d7138448dd4d734
        uses: dbelyaev/action-checkstyle@v1.2.0
